stages:
  clean:
    cmd: uv run python clean.py
    deps:
      - clean.py
      - data/raw/events.csv
    outs:
      - data/clean/events.csv

  transform:
    cmd: uv run python transform.py
    deps:
      - transform.py
      - data/clean/events.csv
    outs:
      - data/transformed/events.csv

  features:
    cmd: uv run python features.py
    deps:
      - features.py
      - data/transformed/events.csv
    outs:
      - data/features/events.csv